### IIMPORTAR LIBRERIAS

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

##### Se consideran todas las variables y se realiza el approach 3
#### Se incrementa el número de neuronas por capas como en los ficheros anteriores 60/120/60 (antes 38/76/38) - epochs = 500

### CARGAR LIBRERIAS DESDE .CSV

In [2]:
path_base = "C:\\Users\\fermi\\UOC\\Master UOC. Posgrado en inteligencia de negocio\\TFM\\Ficheros"
dataset_0 = pd.read_csv(path_base + "\diabetic_set2.csv")

In [3]:
dataset_0.shape

(71515, 50)

In [4]:
dataset_3 = dataset_0[["race","gender","admission_type_id","discharge_disposition_id","admission_source_id","time_in_hospital","num_lab_procedures","num_procedures","num_medications","number_outpatient","number_emergency","number_inpatient","number_diagnoses","max_glu_serum","A1Cresult","metformin","repaglinide","glimepiride","glipizide","glyburide","pioglitazone","rosiglitazone","insulin","change","diabetesMed","age2","diag_1_3","readmitted2_num"]]

In [5]:
dataset_3.columns

Index(['race', 'gender', 'admission_type_id', 'discharge_disposition_id',
       'admission_source_id', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'number_diagnoses',
       'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'glimepiride',
       'glipizide', 'glyburide', 'pioglitazone', 'rosiglitazone', 'insulin',
       'change', 'diabetesMed', 'age2', 'diag_1_3', 'readmitted2_num'],
      dtype='object')

In [6]:
dataset_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71515 entries, 0 to 71514
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   race                      71515 non-null  object
 1   gender                    71515 non-null  object
 2   admission_type_id         71515 non-null  int64 
 3   discharge_disposition_id  71515 non-null  int64 
 4   admission_source_id       71515 non-null  int64 
 5   time_in_hospital          71515 non-null  int64 
 6   num_lab_procedures        71515 non-null  int64 
 7   num_procedures            71515 non-null  int64 
 8   num_medications           71515 non-null  int64 
 9   number_outpatient         71515 non-null  int64 
 10  number_emergency          71515 non-null  int64 
 11  number_inpatient          71515 non-null  int64 
 12  number_diagnoses          71515 non-null  int64 
 13  max_glu_serum             71515 non-null  object
 14  A1Cresult             

### TRANSFORMACIÓN DE VARIABLES CATEGÓRICAS A NUMÉRICAS

In [7]:
dataset_4 = pd.get_dummies(dataset_3, columns=["race","gender","max_glu_serum","A1Cresult","metformin","repaglinide","glimepiride","glipizide","glyburide","pioglitazone","rosiglitazone","insulin","change","diabetesMed","age2","diag_1_3"], prefix=["race","gend","max_","A1Cr","metf","repa","glir","gliz","glyb","piog","rosi","insu","chan","diab","age2","diag"])

In [8]:
dataset_4.iloc[0]

admission_type_id            2
discharge_disposition_id     1
admission_source_id          1
time_in_hospital             8
num_lab_procedures          77
                            ..
diag_Lesion                  0
diag_Musculoesqueletico      0
diag_Neoplasias              0
diag_Otros                   0
diag_Respiratorio            0
Name: 0, Length: 75, dtype: int64

In [9]:
dataset_4.shape

(71515, 75)

In [10]:
# dataset_4.to_excel('v16.fin.xlsx', index = False)

### ESTABLECER VARIABLES DEPENDIENTES E INDEPENDIENTES

In [11]:
X = dataset_4.iloc[:, np.r_[0:11, 12:74,74]]
y = dataset_4.iloc[:,-64].values
X.head(3)

admission_type_id  discharge_disposition_id  admission_source_id  \
0                  2                         1                    1   
1                  3                         1                    1   
2                  1                         3                    7   

   time_in_hospital  num_lab_procedures  num_procedures  num_medications  \
0                 8                  77               6               33   
1                 2                  49               1               11   
2                 4                  68               2               23   

   number_outpatient  number_emergency  number_inpatient  ...  age2_[60-100)  \
0                  0                 0                 0  ...              0   
1                  0                 0                 0  ...              0   
2                  0                 0                 0  ...              1   

   diag_Circulatorio  diag_Diabetes  diag_Digestivo  diag_Genitourinario  \
0                  1              0               0                    0   
1                  0              0               0                    0   
2                  0              0               0                    0   

   diag_Lesion  diag_Musculoesqueletico  diag_Neoplasias  diag_Otros  \
0            0                        0                0           0   
1            0                        1                0           0   
2            1                        0                0           0   

   diag_Respiratorio  
0                  0  
1                  0  
2                  0  

[3 rows x 74 columns]

In [12]:
X.columns

Index(['admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'num_lab_procedures', 'num_procedures',
       'num_medications', 'number_outpatient', 'number_emergency',
       'number_inpatient', 'number_diagnoses', 'race_AfricanAmerican',
       'race_Asian', 'race_Caucasian', 'race_Hispanic', 'race_Other',
       'gend_Female', 'gend_Male', 'max__>200', 'max__>300', 'max__None',
       'max__Norm', 'A1Cr_>7', 'A1Cr_>8', 'A1Cr_None', 'A1Cr_Norm',
       'metf_Down', 'metf_No', 'metf_Steady', 'metf_Up', 'repa_Down',
       'repa_No', 'repa_Steady', 'repa_Up', 'glir_Down', 'glir_No',
       'glir_Steady', 'glir_Up', 'gliz_Down', 'gliz_No', 'gliz_Steady',
       'gliz_Up', 'glyb_Down', 'glyb_No', 'glyb_Steady', 'glyb_Up',
       'piog_Down', 'piog_No', 'piog_Steady', 'piog_Up', 'rosi_Down',
       'rosi_No', 'rosi_Steady', 'rosi_Up', 'insu_Down', 'insu_No',
       'insu_Steady', 'insu_Up', 'chan_Ch', 'chan_No', 'diab_No', 'diab_Yes',
       'ag

In [13]:
X.shape

(71515, 74)

In [14]:
y

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

### DATOS DE ENTRENAMIENTO Y DE TEST

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state =1)

#### Datos test vs Datos train. Casos totales, Casos Positivos y Casos Negativos

In [16]:
total = len(y_train)
one_count = np.sum(y_train)
one_count_pct=one_count/total
zero_count = total - one_count
zero_count_pct = 1 - one_count_pct

print("Total registros del train", total)
print("Total positivos en y_train: ", one_count)
print("Porcentaje de positivos: ", round(one_count_pct*100,2), "%")
print("Total negativos en y_train: ", zero_count)
print("Porcentaje de negativos", round(zero_count_pct*100,2), "%")

Total registros del train 57212
Total positivos en y_train:  5029
Porcentaje de positivos:  8.79 %
Total negativos en y_train:  52183
Porcentaje de negativos 91.21 %


In [17]:
total = len(y_test)
one_count = np.sum(y_test)
one_count_pct=one_count/total
zero_count = total - one_count
zero_count_pct = 1 - one_count_pct

print("Total registros del test", total)
print("Total positivos en y_test: ", one_count)
print("Porcentaje de positivos: ", round(one_count_pct*100,2), "%")
print("Total negativos en y_test: ", zero_count)
print("Porcentaje de negativos", round(zero_count_pct*100,2), "%")

Total registros del test 14303
Total positivos en y_test:  1264
Porcentaje de positivos:  8.84 %
Total negativos en y_test:  13039
Porcentaje de negativos 91.16 %


#### ESTANDARIZACIÓN DE DATOS

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#### Arbol de decisión. Fase de entrenamiento

In [19]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='gini', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0)

#### Árbol de decisión. Fase de predicción

In [20]:
y_pred = classifier.predict(X_test)
print(y_test- y_pred)
print(sum(y_pred-y_test))


[0 0 0 ... 0 0 0]
250


### MATRIZ DE CONFUSIÓN

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11697  1342]
 [ 1092   172]]


In [22]:
accuracy_score(y_test, y_pred)
TP = cm[1][1]
TN = cm[0][0]
FN = cm[1][0]
FP = cm[0][1]
total_casos = TP + FP + TN + FN
print("Total Casos =", total_casos)
print("Verdaderos Positivos:", TP)
print("Verdaderos Negativos:", TN)
print("Falsos Positivos: ", FP)
print("Falsos Negativos: ", FN)
exactitud = ((TP+TN) / (TP+FP+TN+FN))
print(f"Exactitud = {round(exactitud,2)}")
precision = (TP / (TP+FP))
print(f"Precisión = {round(precision,2)}")
sensibilidad = (TP / (TP + FN))
print(f"Sensibilidad = {round(sensibilidad,2)}")
especificidad = (TN/(TN+FP))
print(f"Especificidad = {round(especificidad, 2)}")

Total Casos = 14303
Verdaderos Positivos: 172
Verdaderos Negativos: 11697
Falsos Positivos:  1342
Falsos Negativos:  1092
Exactitud = 0.83
Precisión = 0.11
Sensibilidad = 0.14
Especificidad = 0.9
